/**
 * MCP tools for workspace operations.
 * get_skill_gen_plan — returns the prompt for generating CLAUDE.md + .claude/skills/
 * save_sa_flow — saves a Mermaid SA flow diagram generated by subagent
 */
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import fs from 'node:fs';
import path from 'node:path';
import { getMcpDb } from '../db.js';
import { notifyWebServer } from '../notify.js';
import { saveFlowFile } from '../flow-gate.js';

export function registerWorkspaceTools(server: McpServer): void {

  // ── get_skill_gen_plan ────────────────────────────────────
  server.tool(
    'get_skill_gen_plan',
    'Get the full prompt for generating or enhancing CLAUDE.md and .claude/skills/ for a workspace. Dispatches an Opus-level subagent to deep-read the codebase and document its patterns, conventions, and hidden rules.',
    {
      projectId: z.string().describe('The project ID'),
      workspaceType: z.enum(['frontend', 'backend']).describe('Which workspace to generate skills for'),
    },
    { title: 'Get Skill Generation Plan', readOnlyHint: true, openWorldHint: false },
    async ({ projectId, workspaceType }) => {
      const db = getMcpDb();

      const project = db.prepare('SELECT * FROM projects WHERE id = ?').get(projectId) as {
        id: string; name: string; working_dir: string;
        frontend_path: string | null; backend_path: string | null;
      } | undefined;

      if (!project) {
        return { content: [{ type: 'text' as const, text: `Error: Project "${projectId}" not found` }], isError: true };
      }

      const workspacePath = workspaceType === 'frontend'
        ? (project.frontend_path || project.working_dir)
        : (project.backend_path || project.working_dir);

      // Detect mode — recognize both official folder skills (<skill-name>/SKILL.md)
      // and legacy flat .md skill files
      const hasClaudeMd = fs.existsSync(path.join(workspacePath, 'CLAUDE.md'));
      const skillsDir = path.join(workspacePath, '.claude', 'skills');
      const hasSkillsDir = fs.existsSync(skillsDir);
      const hasSkills = hasSkillsDir && fs.readdirSync(skillsDir, { withFileTypes: true }).some(entry =>
        (entry.isFile() && entry.name.endsWith('.md')) ||
        (entry.isDirectory() && fs.existsSync(path.join(skillsDir, entry.name, 'SKILL.md')))
      );
      const mode: 'create' | 'enhance' = (hasClaudeMd || hasSkills) ? 'enhance' : 'create';

      // Active project experience notes (前人踩坑教訓) — must be woven into the generated docs
      const notes = db.prepare(`
        SELECT category, content FROM project_notes
        WHERE project_id = ? AND active = 1
        ORDER BY created_at ASC
      `).all(projectId) as Array<{ category: string | null; content: string }>;

      const prompt = buildSkillGenPrompt(workspaceType, mode, hasClaudeMd, hasSkills, notes);

      const plan = `**Skill Generation Plan**
**Project:** ${project.name}
**Workspace:** ${workspacePath}
**Type:** ${workspaceType}
**Mode:** ${mode} (${mode === 'create' ? '從零建立' : '增強現有內容'})

> **執行流程（orchestrator 依序執行，讓 subagent 的進度回報有 taskId 可用）：**
> 1. 呼叫 \`create_task(projectId="${project.id}", title="Skill 產生：${workspaceType} workspace", label="${workspaceType}", taskType="other")\` 取得 taskId
> 2. 呼叫 \`update_task_status(taskId, "in_progress")\`
> 3. 使用 Agent tool 派出 subagent，工作目錄設為 \`${workspacePath}\`，將以下 prompt 作為任務傳入，**並在 prompt 開頭附上步驟 1 取得的實際 taskId**，指示 subagent 用 \`report_output(taskId="<實際taskId>", content="...")\` 與 \`report_milestone(taskId="<實際taskId>", milestone="...")\` 回報進度到 Web UI
> 4. subagent 完成後呼叫 \`update_task_status(taskId, "completed", summary="產出檔案清單")\`；失敗則呼叫 \`update_task_status(taskId, "failed", summary="失敗原因")\`

---

${prompt}`;

      return { content: [{ type: 'text' as const, text: plan }] };
    },
  );

  // ── save_sa_flow ──────────────────────────────────────────
  server.tool(
    'save_sa_flow',
    'Save a Mermaid SA (System Analysis) flow diagram generated from an SA spec document. The diagram will be cached and viewable in the Web UI\'s SA Flow panel.',
    {
      projectId: z.string().describe('The project ID'),
      taskId: z.string().optional().describe('Optional task ID this flow is associated with'),
      filename: z.string().describe('Source SA document filename (e.g., "SPEC_WA05_經手表單查詢_v0.1.docx")'),
      mermaidContent: z.string().describe('The Mermaid flowchart content (flowchart TD format)'),
    },
    { title: 'Save SA Flow', readOnlyHint: false, destructiveHint: false, openWorldHint: false },
    async ({ projectId, taskId, filename, mermaidContent }) => {
      if (!mermaidContent.trim()) {
        return { content: [{ type: 'text' as const, text: 'Error: mermaidContent is empty' }], isError: true };
      }

      const saved = saveFlowFile({
        projectId,
        taskId,
        flowType: 'spec',
        role: 'default',
        mermaidContent,
        filename,
      });

      // Notify Web Server
      await notifyWebServer({
        event: 'sa-flow.saved',
        data: { projectId, taskId: taskId || null, filename, flowPath: saved.flowPath },
      });

      return { content: [{ type: 'text' as const, text: `SA Flow saved: ${saved.flowPath}\nUse the Web UI's SA Flow button to view it.` }] };
    },
  );
}

/**
 * Build the skill generation prompt.
 */
function buildSkillGenPrompt(
  workspaceType: 'frontend' | 'backend',
  mode: 'create' | 'enhance',
  hasClaudeMd: boolean,
  hasSkills: boolean,
  notes: Array<{ category: string | null; content: string }> = [],
): string {
  const lang = workspaceType === 'frontend' ? '前端' : '後端';

  const modeInstruction = mode === 'create'
    ? `此工作目錄**尚無** CLAUDE.md 或 .claude/skills/，從零開始建立。`
    : `此工作目錄**已有**${hasClaudeMd ? ' CLAUDE.md' : ''}${hasSkills ? ' .claude/skills/' : ''}，先讀取現有內容，找出缺漏或過時的部分補強。現有正確的內容不要刪除，只新增或修正。${hasClaudeMd && !hasSkills ? '\n注意：有 CLAUDE.md 但尚無 .claude/skills/，需要建立 skills 目錄和檔案。' : ''}${hasSkills ? '\n若 .claude/skills/ 下發現既有的**平面 .md skill 檔**（如 .claude/skills/foo.md），遷移成官方資料夾格式 .claude/skills/foo/SKILL.md：內容保留，frontmatter 只留 name/description，遷移完成後移除舊的平面檔。' : ''}`;

  const notesSection = notes.length === 0 ? '' : `
---

## 專案經驗筆記（使用者與先前任務累積的踩坑教訓，必須融入文件）
${notes.map(n => `- ${n.category ? `[${n.category}] ` : ''}${n.content}`).join('\n')}

要求：這些教訓必須反映在 CLAUDE.md 的禁止清單/潛規則章節或對應的 skill 中（用你的話語重寫、補充程式碼佐證，不要照抄）。enhance 模式時，比對現有文件是否已涵蓋這些教訓，缺的補上。
`;

  return `你是一位深度理解真實工程現場的資深${lang}架構師。
你的任務是：**深度閱讀這個專案的程式碼，把它的「開發方式、習慣、潛規則」全部文件化**，讓未來的 AI agent 讀了之後，能像一個熟悉這個專案三個月的工程師一樣開發——不踩雷、不重複造輪子、風格一致。

${modeInstruction}

---

## 分析流程

### Phase 1：摸清全局
用 Glob、Grep 工具掃描整個專案：
- 資料夾結構、檔案命名規律
- package.json（依賴、scripts）、tsconfig、build 工具設定
- 有沒有現成的 CLAUDE.md、.claude/、README、ADR、docs/
- 有沒有 lint/format 設定（eslint、prettier、stylelint）

### Phase 2：深讀程式碼
**不要只看一兩個檔案。要跨越不同功能模組，廣泛取樣，抓出「這個專案一貫的做法」。**

每個維度都要看實際程式碼，提取真實的 pattern，不要假設：
${workspaceType === 'frontend' ? `
- 元件：怎麼定義 props？用 interface 還是 type？有沒有統一的 FC 寫法？
- Hooks：custom hook 放哪？命名規則？怎麼處理 side effect？
- 狀態：用什麼管理（zustand/redux/context/jotai/...）？store 結構怎麼組？action 怎麼命名？
- API 呼叫：有沒有封裝的 http client / api layer？錯誤怎麼處理？loading/error state 慣例？
- Form：react-hook-form / formik / 純 state？validation 在哪一層？error message 怎麼顯示？
- 路由：router 怎麼組？有沒有 guard？lazy load 怎麼做？navigate 怎麼呼叫？
- 共用元件：shared/components 有哪些？怎麼 import？有沒有 barrel index？哪些最常被誤重複實作？
- 樣式：Tailwind / CSS modules / styled-components？className 組合習慣？有沒有 design token？
- 型別：types/interfaces 放哪？有沒有 API response 型別生成？enum 還是 union string？
- Import：路徑 alias 配置？相對 vs 絕對偏好？barrel import 習慣？
- 測試：框架？test 檔放哪？命名慣例？mock 怎麼做？有沒有 shared test utils？
- i18n：有沒有？key 命名？t() 用法？哪些地方不需要翻譯？
- 其他觀察到的強烈慣例
` : `
- 分層：controller / service / repository（或其他分層）如何切？各層職責邊界在哪？
- 框架：NestJS / Express / Fastify / 其他？有哪些特有的 pattern（decorator、guard、interceptor、pipe...）？
- DB：用哪個 ORM？query 怎麼寫？N+1 怎麼處理？transaction 怎麼開？migration 規則？
- API：路由命名規則？prefix？versioning？request body 怎麼 validate（zod/class-validator/joi/...）？response 格式統一嗎？
- 認證授權：JWT/session？token 怎麼驗？role/permission 怎麼設計？guard 在哪層？
- 錯誤處理：有沒有 global exception filter？自訂 error class 怎麼繼承？HTTP status 對應規則？
- DTO/Entity：命名規則？validation decorator 怎麼放？序列化設定（class-transformer / exclude 等）？
- Log / Audit：用哪個 logger？哪些操作需要 audit？log 格式？
- 設定：env 怎麼讀？有沒有 config service / module？secrets 管理方式？
- 測試：unit vs integration？mock DB 策略？repository mock 怎麼做？test data 怎麼建？
- 其他觀察到的強烈慣例
`}

### Phase 3：挖潛規則（最重要）
讀程式碼時特別留意以下，這些是新 agent 最容易出錯的地方：

1. **刻意的奇怪寫法** — 看起來不合理但有原因的 workaround，標明「不要動、不要優化」和原因
2. **禁止清單** — 明確不能用的套件、寫法、模式（要有具體理由）
3. **已有但容易被忽略的 utility/helper** — 新 agent 最常重複造的輪子
4. **版本或環境限制** — 某些新 API 因版本鎖定無法使用
5. **隱性的業務規則** — 某些看似技術的決定其實是業務要求（例如：特定欄位不能為空、某操作必須寫 audit log）
6. **開發順序 / 依賴關係** — 做某功能之前必須先做什麼（例如：改 DB 前要先跑 migration）
${notesSection}
---

## 輸出原則

**目標只有一個：讓未來的 AI agent 讀完這些文件，立刻知道「在這個專案要怎麼開發」。**

**硬性要求：每一條慣例、禁止事項、潛規則，都必須附上 1–2 個實際檔案路徑（相對路徑）作為證據**，例如：\`- 禁止直接 fetch，一律走 src/api/client.ts 的 apiClient（見 src/pages/Order/List.tsx:42 的用法）\`。找不到程式碼佐證的規則不要寫。

不要套固定模板。根據你在這個專案實際發現的東西，自己判斷：
- CLAUDE.md 要寫哪些章節、寫多深
- 要建多少個 skill 檔案、每個聚焦什麼主題
- 什麼值得單獨拆成一個 skill（有反覆使用價值的、容易踩雷的、需要查表的）

### CLAUDE.md 撰寫方向
- 開頭快速說清楚這是什麼專案、用什麼技術棧
- 架構概覽要讓人知道「要找什麼去哪個資料夾」
- 規範類的內容要具體，配程式碼範例，不要只說「遵循 XXX 風格」
- 禁止事項和 workaround 要獨立、醒目，是最容易救命的部分
- 寧可寫少但準確，不要寫多但模糊
- **必須包含「可用 Skills」章節**：列出所有建立的 skill 名稱、描述、什麼情況下應該使用
- **必須包含「開發前必讀 / 開工檢查清單」章節**（硬性要求）：內容是接到任務後、寫 code 之前，依序要看哪些東西——例如：
  1. 相關模組的現有實作範例（指出去哪個資料夾找同類功能，如「做查詢頁先看 src/pages/Order/ 的既有寫法」）
  2. 共用元件 / utility 清單（先確認有沒有現成的，不要重複造輪子）
  3. 對應要先讀的 .claude/skills/ 是哪幾個 skill
  4. 有沒有 mock / 測試資料 / 環境設定要先建
  讓 agent 開工前照這份清單走一遍，再開始寫 code。

### .claude/skills/ 撰寫方向
每個 skill 聚焦一個明確的主題，讓 agent 在需要的時候能精確叫出來。

**格式（強制，Claude Code 官方 skill 格式）：每個 skill 一個資料夾，內含 \`SKILL.md\`** — 即 \`.claude/skills/<skill-name>/SKILL.md\`。不要建立平面的 \`.claude/skills/<name>.md\` 檔案。

自己決定要建哪些，以下是**可能的方向**（不是必填清單）：
- 程式碼慣例 / 命名規則
- 反模式 / 禁止清單
- 共用元件使用指南
- 某個複雜流程的 step-by-step
- 特定技術的專案內用法
- 測試策略
- 任何你覺得「新人最需要知道」的主題

每個 SKILL.md 必須有 frontmatter（只放 name 和 description 兩個欄位）：
\`\`\`markdown
---
name: skill-name
description: 什麼情況下應該使用這個 skill（觸發時機寫具體，agent 靠這一行決定要不要載入）
---
\`\`\`

### 基本原則
- 所有路徑、範例都從實際程式碼提取，不要虛構
- 每條禁止/警告都要有理由
- 找不到的東西不要寫，寧缺勿濫

### 絕對禁止
- **不得執行任何 DB 操作**（SELECT、INSERT、UPDATE、DELETE、DROP、ALTER 等一律禁止）
- **不得修改任何現有程式碼**，只能讀取
- 唯一允許寫入的目標：CLAUDE.md 和 .claude/skills/ 下的 markdown 檔案

### 進度回報
orchestrator 會在任務指示中提供本次任務的 taskId。每完成一個 Phase 用 \`report_output(taskId="<taskId>", content="...")\` 回報；全部完成後用 report_output 回報產出檔案清單。

完成所有檔案後，輸出 [TASK_COMPLETE]`;
}
