import type { Agent, AgentStatus, AgentOutputEvent, AgentProgress } from './agent-types.js';
import type { Task, TaskStatus, TaskType, TaskSource, TaskLabel, DependencyEdge, TaskSummary } from './task-types.js';
import type { ReviewResult } from './review-types.js';
import type { Project, Workspace, DocType, SuperpowersConfig, PlanConfig, AgentPlan, SvnCredentials } from './project-types.js';
import type { AsanaTask, AsanaConnectionStatus, AsanaFetchTasksOptions } from './asana-types.js';
import type { AsanaSyncConfig } from './project-types.js';

// Base envelope for all WebSocket messages
export interface WsMessage {
  type: string;
  id: string;
  timestamp: string;
}

// ============================================
// CLIENT -> SERVER messages
// ============================================

export interface ReviewConfig {
  enabled: boolean;
  skillSource: string; // "auto" or a workspace label
}

export interface WsCreateProject extends WsMessage {
  type: 'project.create';
  payload: {
    projectId?: string;
    name: string;
    workingDir: string;
    frontendPath: string | null;
    backendPath: string | null;
    asanaProjectGid?: string;
    planConfig?: PlanConfig;
  };
}

export interface WsUploadDocument extends WsMessage {
  type: 'project.uploadDocument';
  payload: {
    projectId: string;
    filename: string;
    content: string; // Base64 encoded
    fileType: string;
    docType?: DocType;
    taskId?: string; // If set, file is stored in per-task subfolder
    agentId?: string; // If set, file is stored in per-agent subfolder
  };
}

export interface WsStartExecution extends WsMessage {
  type: 'project.startExecution';
  payload: {
    projectId: string;
    taskId?: string;
    requirement?: string;
    model?: string;
    role?: string;
  };
}

export interface WsPauseExecution extends WsMessage {
  type: 'project.pause';
  payload: { projectId: string };
}

export interface WsResumeExecution extends WsMessage {
  type: 'project.resume';
  payload: { projectId: string };
}

export interface WsInterviewResponse extends WsMessage {
  type: 'interview.userResponse';
  payload: {
    projectId: string;
    message: string;
  };
}

export interface WsInterviewConfirm extends WsMessage {
  type: 'interview.confirmSpec';
  payload: {
    projectId: string;
    confirmed: boolean;
    modifications?: string;
  };
}

export interface WsAgentAction extends WsMessage {
  type: 'agent.action';
  payload: {
    agentId: string;
    action: 'stop' | 'restart' | 'pause';
  };
}

export interface WsAgentCommand extends WsMessage {
  type: 'agent.command';
  payload: {
    agentId: string;
    command: string;
  };
}

export interface WsInterventionResolve extends WsMessage {
  type: 'intervention.resolve';
  payload: {
    interventionId: string;
    decision: 'approve' | 'reject' | 'modify';
    userInput?: string;
  };
}

export interface WsTaskOverride extends WsMessage {
  type: 'task.override';
  payload: {
    taskId: string;
    action: 'retry' | 'skip' | 'reassign';
    newAgentRole?: string;
  };
}

export interface WsDeleteProject extends WsMessage {
  type: 'project.delete';
  payload: {
    projectId: string;
  };
}

export interface WsUpdateProject extends WsMessage {
  type: 'project.update';
  payload: {
    projectId: string;
    name?: string;
    frontendPath?: string | null;
    backendPath?: string | null;
    asanaProjectGid?: string | null;
    dbConnectionString?: string | null;
    configJson?: string | null;
  };
}

export interface WsDeleteAgent extends WsMessage {
  type: 'agent.delete';
  payload: {
    agentId: string;
  };
}

export interface WsUpdateAgent extends WsMessage {
  type: 'agent.update';
  payload: {
    agentId: string;
    title?: string | null;
  };
}

export interface WsAddAgent extends WsMessage {
  type: 'agent.add';
  payload: {
    projectId: string;
    agentId?: string; // Pre-generated by client so uploaded files can be linked to this agent
    role: string;
    prompt: string;
    model?: string;
    workingDir?: string;
    useWorkspaceSkills?: boolean;
    superpowersFeatures?: string[];
  };
}

export interface WsDeleteDocument extends WsMessage {
  type: 'project.deleteDocument';
  payload: {
    projectId: string;
    documentId: string;
  };
}

export interface WsPlanAction extends WsMessage {
  type: 'agent.planAction';
  payload: {
    agentId: string;
    planId: string;
    action: 'approve' | 'reject';
    feedback?: string;
  };
}

// v2: Task management messages
export interface WsTaskCreate extends WsMessage {
  type: 'task.create';
  payload: {
    projectId: string;
    title: string;
    description?: string;
    taskType: TaskType;
    label: TaskLabel;
    source?: TaskSource;
    sourceRef?: string;
    specUrl?: string;
    preferredModel?: string;
    parentName?: string;
  };
}

export interface WsTaskDelete extends WsMessage {
  type: 'task.delete';
  payload: {
    projectId: string;
    taskId: string;
  };
}

export interface WsTaskUpdate extends WsMessage {
  type: 'task.update';
  payload: {
    projectId: string;
    taskId: string;
    title?: string;
    description?: string | null;
    specUrl?: string | null;
    label?: TaskLabel;
    taskType?: TaskType;
    status?: TaskStatus;
    preferredModel?: string | null;
    parentName?: string | null;
  };
}

export interface WsTaskBulkDeleteBySource extends WsMessage {
  type: 'task.bulkDeleteBySource';
  payload: {
    projectId: string;
    source: TaskSource;
  };
}

// v2: Workspace messages
export interface WsWorkspaceScan extends WsMessage {
  type: 'workspace.scan';
  payload: {
    projectId: string;
    path: string;
    workspaceType: 'frontend' | 'backend';
  };
}

export interface WsWorkspaceGenerateSkills extends WsMessage {
  type: 'workspace.generateSkills';
  payload: {
    projectId: string;
    path: string;
    workspaceType: 'frontend' | 'backend';
  };
}

// ============================================
// SVN Browse messages
// ============================================

export interface WsSvnBrowse extends WsMessage {
  type: 'svn.browse';
  payload: {
    projectId: string;
    /** SVN directory URL to list. If omitted, uses project's svnConfig root based on specType. */
    svnUrl?: string;
    /** Which SVN root to use: 'frontend' or 'backend' */
    specType?: 'frontend' | 'backend';
  };
}

export interface WsSvnBrowseResult extends WsMessage {
  type: 'svn.browseResult';
  payload: {
    svnUrl: string;
    entries: Array<{ name: string; isDir: boolean; fullUrl: string }>;
    error?: string;
  };
}

export interface WsSvnPreview extends WsMessage {
  type: 'svn.preview';
  payload: {
    projectId: string;
    /** Function code to search for (e.g. "IC01", "OV0101"). If omitted, extracted from taskId's title/parentName. */
    functionCode?: string;
    taskId?: string;
    taskLabel?: string;
  };
}

export interface WsSvnPreviewResult extends WsMessage {
  type: 'svn.previewResult';
  payload: {
    functionCode: string;
    rootCode: string;
    files: Array<{ filename: string; svnUrl: string; svnRoot: 'frontend' | 'backend' }>;
    error?: string;
  };
}

// ============================================
// ASANA MCP messages (CLIENT -> SERVER)
// ============================================

export interface WsAsanaFetchTasks extends WsMessage {
  type: 'asana.fetchTasks';
  payload: AsanaFetchTasksOptions;
}

export interface WsAsanaCheckConnection extends WsMessage {
  type: 'asana.checkConnection';
  payload: Record<string, never>;
}

export interface WsAsanaFetchProjects extends WsMessage {
  type: 'asana.fetchProjects';
  payload: {
    workspace?: string;
  };
}

export interface WsAsanaFetchMyProjectTasks extends WsMessage {
  type: 'asana.fetchMyProjectTasks';
  payload: {
    projectGid: string;
    includeCompleted?: boolean;
  };
}

export interface WsAsanaFetchTaskStories extends WsMessage {
  type: 'asana.fetchTaskStories';
  payload: {
    taskGid: string;
  };
}

export interface WsAsanaSyncNow extends WsMessage {
  type: 'asana.syncNow';
  payload: {
    projectId: string;
  };
}

export interface WsAsanaUpdateSyncConfig extends WsMessage {
  type: 'asana.updateSyncConfig';
  payload: {
    projectId: string;
    config: AsanaSyncConfig;
  };
}

export interface WsAgentResume extends WsMessage {
  type: 'agent.resume';
  payload: {
    agentId: string;
    prompt?: string;
  };
}

export interface WsStartQuickTask extends WsMessage {
  type: 'project.startQuickTask';
  payload: {
    workingDir: string;
    taskType: 'bug' | 'feature' | 'refactor' | 'other';
    role: 'backend' | 'frontend' | 'devops' | 'testing';
    description: string;
    errorLog?: string;
    relatedFiles?: string[];
    model?: string;
    useWorkspaceSkills?: boolean;
  };
}

// ============================================
// Mockup messages
// ============================================

export interface WsMockupReload extends WsMessage {
  type: 'mockup.reload';
  payload: {
    projectId: string;
    filenames: string[];  // e.g. ['sl01-查詢.html', 'sl01-新增.html']
    axshareUrl: string;
  };
}

// ============================================
// Global config messages
// ============================================

export interface WsGetGlobalConfig extends WsMessage {
  type: 'config.get';
  payload: Record<string, never>;
}

export interface WsSetGlobalConfig extends WsMessage {
  type: 'config.set';
  payload: {
    key: string;
    value: string;
  };
}

export interface WsSetSvnCredentials extends WsMessage {
  type: 'config.setSvnCredentials';
  payload: SvnCredentials;
}

export interface WsGlobalConfigState extends WsMessage {
  type: 'config.state';
  payload: {
    svnUsername: string;
    hasSvnPassword: boolean;
  };
}

export type ClientMessage =
  | WsCreateProject
  | WsUploadDocument
  | WsStartExecution
  | WsStartQuickTask
  | WsPauseExecution
  | WsResumeExecution
  | WsInterviewResponse
  | WsInterviewConfirm
  | WsAgentAction
  | WsAgentCommand
  | WsAgentResume
  | WsInterventionResolve
  | WsTaskOverride
  | WsDeleteProject
  | WsUpdateProject
  | WsDeleteAgent
  | WsUpdateAgent
  | WsAddAgent
  | WsDeleteDocument
  | WsPlanAction
  | WsTaskCreate
  | WsTaskDelete
  | WsTaskUpdate
  | WsTaskBulkDeleteBySource
  | WsWorkspaceScan
  | WsWorkspaceGenerateSkills
  | WsSvnBrowse
  | WsSvnPreview
  | WsAsanaFetchTasks
  | WsAsanaFetchMyProjectTasks
  | WsAsanaFetchProjects
  | WsAsanaCheckConnection
  | WsAsanaFetchTaskStories
  | WsAsanaSyncNow
  | WsAsanaUpdateSyncConfig
  | WsGetGlobalConfig
  | WsSetGlobalConfig
  | WsSetSvnCredentials;

// ============================================
// SERVER -> CLIENT messages
// ============================================

export interface WsProjectState extends WsMessage {
  type: 'project.state';
  payload: {
    project: Project;
    tasks: Task[];
    agents: Agent[];
    dependencies: DependencyEdge[];
  };
}

export interface WsProjectsList extends WsMessage {
  type: 'projects.list';
  payload: {
    projects: Project[];
  };
}

export interface WsAgentOutput extends WsMessage {
  type: 'agent.output';
  payload: AgentOutputEvent;
}

export interface WsAgentStatusChange extends WsMessage {
  type: 'agent.statusChange';
  payload: {
    agentId: string;
    previousStatus: AgentStatus;
    newStatus: AgentStatus;
    reason?: string;
  };
}

export interface WsTaskStatusChange extends WsMessage {
  type: 'task.statusChange';
  payload: {
    taskId: string;
    previousStatus: TaskStatus;
    newStatus: TaskStatus;
    assignedAgentId?: string;
  };
}

export interface WsEventBusNotification extends WsMessage {
  type: 'eventbus.notification';
  payload: {
    eventType: string;
    source: string;
    target: string;
    data: Record<string, unknown>;
  };
}

export interface WsInterventionRequest extends WsMessage {
  type: 'intervention.request';
  payload: {
    interventionId: string;
    agentId: string;
    agentRole: string;
    taskId: string | null;
    reason: string;
    context: string;
    suggestedActions: string[];
  };
}

export interface WsInterviewQuestion extends WsMessage {
  type: 'interview.question';
  payload: {
    projectId: string;
    question: string;
    questionIndex: number;
    totalEstimated: number;
  };
}

export interface WsSpecDraft extends WsMessage {
  type: 'interview.specDraft';
  payload: {
    projectId: string;
    saDocument: string;
    sdDocument: string;
    extractedTasks: TaskSummary[];
  };
}

export interface WsError extends WsMessage {
  type: 'error';
  payload: {
    code: string;
    message: string;
    relatedEntity?: string;
  };
}

export interface WsDocumentsList extends WsMessage {
  type: 'project.documents';
  payload: {
    projectId: string;
    documents: Array<{
      id: string;
      filename: string;
      docType: 'SA' | 'SD';
    }>;
  };
}

export interface WsAgentPlanReady extends WsMessage {
  type: 'agent.planReady';
  payload: {
    plan: AgentPlan;
    agentRole: string;
  };
}

export interface WsAgentPlansList extends WsMessage {
  type: 'agent.plans';
  payload: {
    projectId: string;
    plans: AgentPlan[];
  };
}

export interface WsAgentInitialPrompt extends WsMessage {
  type: 'agent.initialPrompt';
  payload: {
    agentId: string;
    prompt: string;
    role: string;
  };
}

// v3: Agent progress
export interface WsAgentProgress extends WsMessage {
  type: 'agent.progress';
  payload: AgentProgress;
}

// v3: Review completed with structured result
export interface WsReviewCompleted extends WsMessage {
  type: 'review.completed';
  payload: {
    projectId: string;
    taskId: string;
    agentId: string;
    result: ReviewResult;
  };
}

// v3: Task retrying after failed review
export interface WsTaskRetrying extends WsMessage {
  type: 'task.retrying';
  payload: {
    taskId: string;
    projectId: string;
    retryCount: number;
    reason: string;
  };
}

// v2: Task list response
export interface WsTaskCreated extends WsMessage {
  type: 'task.created';
  payload: {
    task: Task;
  };
}

export interface WsTaskList extends WsMessage {
  type: 'task.list';
  payload: {
    projectId: string;
    tasks: Task[];
  };
}

// v2: Workspace scan result
export interface WsWorkspaceScanResult extends WsMessage {
  type: 'workspace.scanResult';
  payload: {
    projectId: string;
    workspaceType: 'frontend' | 'backend';
    path: string;
    hasClaudeMd: boolean;
    hasClaudeDir: boolean;
    skills: Array<{ name: string; filename: string; path: string }>;
  };
}

// ============================================
// ASANA MCP messages (SERVER -> CLIENT)
// ============================================

export interface WsAsanaTasks extends WsMessage {
  type: 'asana.tasks';
  payload: {
    tasks: AsanaTask[];
  };
}

export interface WsAsanaConnectionStatus extends WsMessage {
  type: 'asana.connectionStatus';
  payload: AsanaConnectionStatus;
}

export interface WsAsanaProjects extends WsMessage {
  type: 'asana.projects';
  payload: {
    projects: Array<{ gid: string; name: string }>;
  };
}

export interface WsAsanaTaskStories extends WsMessage {
  type: 'asana.taskStories';
  payload: {
    taskGid: string;
    stories: Array<{
      author: string;
      text: string;
      createdAt: string;
    }>;
  };
}

export interface WsAsanaError extends WsMessage {
  type: 'asana.error';
  payload: {
    code: string;
    message: string;
  };
}

export interface WsAsanaSyncResult extends WsMessage {
  type: 'asana.syncResult';
  payload: {
    projectId: string;
    newTasks: number;
    autoExecuted: number;
    lastSyncAt: string;
  };
}

export interface WsAsanaSyncConfig extends WsMessage {
  type: 'asana.syncConfig';
  payload: {
    projectId: string;
    config: AsanaSyncConfig;
  };
}

export type ServerMessage =
  | WsProjectState
  | WsProjectsList
  | WsDocumentsList
  | WsAgentOutput
  | WsAgentStatusChange
  | WsTaskStatusChange
  | WsEventBusNotification
  | WsInterventionRequest
  | WsInterviewQuestion
  | WsSpecDraft
  | WsAgentPlanReady
  | WsAgentPlansList
  | WsAgentInitialPrompt
  | WsAgentProgress
  | WsReviewCompleted
  | WsTaskRetrying
  | WsTaskCreated
  | WsTaskList
  | WsWorkspaceScanResult
  | WsError
  | WsAsanaTasks
  | WsAsanaProjects
  | WsAsanaConnectionStatus
  | WsAsanaTaskStories
  | WsAsanaError
  | WsAsanaSyncResult
  | WsAsanaSyncConfig
  | WsSvnBrowse
  | WsSvnBrowseResult
  | WsSvnPreview
  | WsSvnPreviewResult
  | WsGlobalConfigState;
